services:
  api:
    build: .
    container_name: solar_api
    env_file: .env
    ports:
      - "5005:5005"
    volumes:
      - .:/app
    depends_on:
      - redis
      - postgres
    restart: always

  redis:
    image: redis:7-alpine
    container_name: solar_redis
    restart: always
    ports:
      - "6379:6379"

  postgres:
    image: postgres:15-alpine
    container_name: solar_postgres
    restart: always
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql   # ✅ init script mount

volumes:
  pgdata:
