server {
  listen 80;
  server_name app.solaroptimizer360.com;

  location ^~ /.well-known/acme-challenge/ {
    root /var/www/certbot;
    allow all; default_type text/plain;
    try_files $uri =404;
  }

  location / { return 301 https://$host$request_uri; }
}
