server {
  listen 80;
  listen [::]:80;
  server_name app.solaroptimizer360.com;

  # ACME challenge – certbot webroot
  location ^~ /.well-known/acme-challenge/ {
    root /var/www/certbot;
    allow all;
    default_type text/plain;
    access_log off;
    try_files $uri =404;
  }

  # Tüm diğer HTTP isteklerini HTTPS'e taşı
  location / {
    return 301 https://app.solaroptimizer360.com$request_uri;
  }
}
