# http{} context içinde yüklenecek global ayarlar

# IP başına istek sınırı: 10 request/s
# limit_req_zone $binary_remote_addr zone=apilimit:10m rate=10r/s;

# WebSocket/Upgrade için Connection headerı
map $http_upgrade $connection_upgrade {
  default keep-alive;
  upgrade websocket;
}
